spring.application.name=gateway-server
server.port=8099

# Config with git server
spring.config.import=optional:configserver:http://localhost:8071

management.endpoints.web.exposure.include=*

# Default information
info.app.name=API Gateway Server Microservices
info.app.decription=Banking Microservices Application
info.app.version=0.0.1

management.info.env.enabled=true
management.endpoint.gateway.access=unrestricted
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.endpoint.health.probes.enabled=true

#join with eureka server
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:9000/eureka/

management.metrics.application= ${spring.application.name}

logging.level.com.banking.gateway-server=DEBUG
logging.pattern.level= "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:7080/realms/master/protocol/openid-connect/certs}
