global:
  configMapName: banking-dev-configmap
  activeProfile: dev
  configServerURL: optional:configserver:http://configserver:8071/
  eurekaServerURL: http://eureka-server:9000/eureka/
  keyCloakURL: http://keycloak/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: ""
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
  otelMetricsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless:9092

configserver:
  extraEnv:
    - name: SPRING_PROFILES_ACTIVE
      value: native
    - name: SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS
      value: classpath:/config
