account-service.msg=account-service
account-service.build-version=2

account-service.mailDetails.hostName=accountservice@corebanking.com
account-service.mailDetails.port=9000
account-service.mailDetails.from=accountservice@gmail.com
account-service.mailDetails.subject=Your account details from sophat core banking Default Environment

account-service.activeBranches[0]=Phnom Penh prod
account-service.activeBranches[1]=Kampong Thoom prod
account-service.activeBranches[2]=Seimreab prod
