account-service.msg=account-service-dev
account-service.build-version=3

account-service.mailDetails.hostName=dev-ountservice@corebanking.com
account-service.mailDetails.port=9000
account-service.mailDetails.from=dev-accountservice@gmail.com
account-service.mailDetails.subject=Your account details from Sophat core banking Dev Environment

account-service.activeBranches[0]=Phnom Penh dev
account-service.activeBranches[1]=Kampong Thoom dev
account-service.activeBranches[2]=Seimreab dev
