account-service.msg=Welcome to core banking service default application
account-service.build-version=4

account-service.mailDetails.hostName=accountservice@corebanking.com
account-service.mailDetails.port=9000
account-service.mailDetails.from=accountservice@gmail.com
account-service.mailDetails.subject=Your account details from sophat core banking Default Environment

account-service.activeBranches[0]=Phnom Penh
account-service.activeBranches[1]=Kampong Thoom
account-service.activeBranches[2]=Seimreab
